import { type SaleModel } from '../models/SaleModel';

export const salesList: SaleModel[] = [
  {
    id: '1',
    customer: '1',
    sale_date: new Date('2021-06-01'),
    total: 100,
    status: 'open',
    saleItems: [
      {
        id: '1',
        sale_id: '1',
        product_id: '1',
        product: 'Cesta básica tipo 1',
        quantity: 1,
        unity: 'un',
        price: 100,
        is_compound: true,
        composition: [
          {
            id: '1',
            product: 'Arroz tipo 1 (composição)',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
          {
            id: '2',
            product: 'Feijão preto (composição)',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
        ],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: true,
        is_deleted: false,
      },
      {
        id: '2',
        sale_id: '1',
        product_id: '2',
        product: 'Feijão preto',
        quantity: 1,
        price: 100,
        unity: 'un',
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '3',
        sale_id: '1',
        product_id: '3',
        product: 'Macarrão',
        quantity: 1,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
    ],
    paymentForm: {
      id: '1',
      name: 'Dinheiro',
      amount: 100,
      icon: 'cash',
    },
  },
  {
    id: '2',
    customer: '2',
    sale_date: new Date('2021-06-02'),
    total: 200,
    status: 'closed',
    saleItems: [
      {
        id: '2',
        sale_id: '2',
        product_id: '2',
        product: 'Cesta básica tipo 2',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [
          {
            id: '3',
            product: 'Macarrão',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
          {
            id: '4',
            product: 'Arroz integral',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
        ],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: true,
        is_deleted: false,
      },
      {
        id: '3',
        sale_id: '2',
        product_id: '3',
        product: 'Macarrão',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '4',
        sale_id: '2',
        product_id: '4',
        product: 'Arroz integral',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '5',
        sale_id: '2',
        product_id: '5',
        product: 'Farinha de trigo',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '6',
        sale_id: '2',
        product_id: '6',
        product: 'Açúcar',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '7',
        sale_id: '2',
        product_id: '7',
        product: 'Sal',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '8',
        sale_id: '2',
        product_id: '8',
        product: 'Café',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '9',
        sale_id: '2',
        product_id: '9',
        product: 'Leite',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
      {
        id: '10',
        sale_id: '2',
        product_id: '10',
        product: 'Óleo de soja',
        quantity: 2,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: false,
        is_deleted: false,
      },
    ],
    paymentForm: {
      id: '2',
      name: 'Cartão de Crédito',
      amount: 200,
      icon: 'credit-card',
    },
  },
  {
    id: '3',
    customer: '3',
    sale_date: new Date('2021-06-03'),
    total: 300,
    status: 'canceled',
    saleItems: [
      {
        id: '3',
        sale_id: '3',
        product_id: '3',
        product: 'Cesta básica tipo 3',
        quantity: 3,
        unity: 'un',
        price: 100,
        is_compound: false,
        composition: [
          {
            id: '5',
            product: 'Farinha de trigo',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
          {
            id: '6',
            product: 'Açúcar',
            quantity: 1,
            price: 100,
            unity: 'un',
            cover_image:
              'https://m.media-amazon.com/images/I/51IcDrBSbUL._AC_SL1200_.jpg',
            is_deleted: false,
          },
        ],
        cover_image:
          'https://http2.mlstatic.com/D_NQ_NP_2X_958796-MLB71636151899_092023-F.webp',
        is_composed: true,
        is_deleted: false,
      },
    ],
    paymentForm: {
      id: '3',
      name: 'Cartão de Débito',
      amount: 300,
      icon: 'credit-card',
    },
  },
];
